name: Build and Publish Docker Image

on:
  push:
    branches: ["**"]
    tags:
      - "v*"
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image
        if: github.event_name != 'pull_request'
        env:
          SHA_TAG: ${{ github.sha }}
          IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/tg-shop-miniapp
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            RELEASE_TAG=${GITHUB_REF##*/}
            echo "Building image for Release Tag = $RELEASE_TAG"
            docker buildx build --platform linux/amd64,linux/arm64 \
              --cache-from type=gha \
              --cache-to type=gha,mode=max \
              -t ${IMAGE_NAME}:$SHA_TAG \
              -t ${IMAGE_NAME}:latest \
              -t ${IMAGE_NAME}:$RELEASE_TAG \
              --push .
          else
            echo "Building image for commit SHA = $SHA_TAG"
            docker buildx build --platform linux/amd64,linux/arm64 \
              --cache-from type=gha \
              --cache-to type=gha,mode=max \
              -t ${IMAGE_NAME}:$SHA_TAG \
              -t ${IMAGE_NAME}:latest \
              --push .
          fi

      - name: Build image for PR
        if: github.event_name == 'pull_request'
        run: |
          echo "Building image for PR (linux/amd64 only, no push)"
          docker buildx build --platform linux/amd64 \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            --load .
